fix: E0107 - missing generics for struct axum_server::Server in from_tcp_with_timeouts
error[E0107]: missing generics for struct `axum_server::Server`
  --> packages/axum-server/src/custom_axum_server.rs:44:55
   |
44 | pub fn from_tcp_with_timeouts(socket: TcpListener) -> Server {
   |                                                       ^^^^^^ expected at least 1 generic argument

Added SocketAddr generic parameter to Server return type and Address trait bound to add_timeouts function.